//! One rupture model, start to finish.
//!
//! Every module before this does one stage. This runs them in order and is the only
//! place that order is written down — in the original it is spread across a
//! 2,859-line `main`.
//!
//! ```text
//!   slip          generate -> truncate -> taper -> scale to moment
//!   reload        the scaled field, back to the wavenumber domain
//!   rake          generated independently of slip
//!   rupture time  correlated with slip, centred, scaled
//!   rise time     correlated with slip, blended toward it near the surface
//!   (two fields   generated by the original and never used -- their draws are
//!    skipped)      consumed, their values are not)
//!   rupture speed from shear speed and depth
//!   onset         eikonal solve, then the rupture-time perturbation
//!   slip rate     one pulse per subfault
//! ```
//!
//! # The order is a contract, not a preference
//!
//! Every stochastic field comes off one generator. Reordering two of them, or
//! skipping one without consuming its draws, changes every field after it — while
//! still producing output that looks entirely plausible. That is why the two unused
//! fields are skipped explicitly rather than deleted, and why this function is the
//! one place the sequence lives.
//!
//! (orig. `genslip_v5.6.2.c:1654-3202`)

use crate::fft::Fft;
use crate::moment::{self, ScaledSlip, SlipScaling, SubfaultSize};
use crate::rise_time::{self, DepthScaling, RiseTimeSpec, RiseTimeStretch, Weighting};
use crate::rng::DrawSource;
use crate::rupture::{self, EikonalSolver, Hypocentre, OnsetAdjustment, SpeedProfile, TravelTimes};
use crate::slip::{self, GridExtents, PerturbationSpec, SpectrumSpec, SubfaultSpacing};
use crate::slip_rate::{self, BetaProfile, SlipRate};
use crate::source::{self, CornerRelation, MagnitudeScale, VelocityModel};
use crate::taper::{EdgeTapers, SlipField};

/// The discretised fault: extents, spacing, and what varies down dip.
///
/// Depth and base rake come from the geometry module rather than being derived here,
/// because a fault is a mesh before it is a grid and only the caller knows how it was
/// discretised.
#[derive(Clone, Debug)]
pub struct FaultGrid {
    pub extents: GridExtents,
    pub spacing: SubfaultSpacing,
    /// One depth per dip row, in km. genslip reads depth per row too — from the first
    /// subfault of each — which is exact for a planar segment.
    pub depth_km: Vec<f32>,
    /// One rake per subfault, in degrees, before the rake field perturbs it.
    pub base_rake_deg: Vec<f32>,
    /// Rupture speed as a fraction of shear-wave speed, per subfault.
    pub velocity_fraction: Vec<f32>,
}

/// What the earthquake is, before any field is drawn.
#[derive(Clone, Copy, Debug)]
pub struct SourceSpec {
    pub magnitude: f32,
    pub magnitude_scale: MagnitudeScale,
    pub corners: CornerRelation,
    pub modified_corners: bool,
    /// Coefficient in `trise = c * 1e-9 * Mo^(1/3)`.
    pub rise_time_coefficient: f32,
    /// Average dip and rake, for the geometry correction.
    pub average_dip_deg: f32,
    pub average_rake_deg: f32,
}

/// How the slip and rake fields are shaped and trimmed.
///
/// Rake lives here rather than in `SourceSpec` because it is a *field*: drawn off the
/// same generator, filtered through the same `spectrum`. Only its normalisation
/// differs, and that difference is the whole of `rake_sigma_deg`.
#[derive(Clone, Copy, Debug)]
pub struct SlipSpec {
    pub spectrum: SpectrumSpec,
    pub tapers: EdgeTapers,
    /// Clip negative slip to zero. Configured on.
    pub truncate_negative: bool,
    /// Minimum slip as a fraction of the mean. Non-positive disables.
    pub water_level: f32,
    /// Standard deviation of the rake field, in **degrees**, about each subfault's
    /// base rake. (orig. `genslip_v5.6.2.c:2068`)
    ///
    /// Not `spectrum.coefficient_of_variation`, which is the *slip* field's spread
    /// and is dimensionless. Handing that to `rake_field` is what `DEFECTS.md` 14
    /// was: every rake came out with a spread of 0.75 degrees where the original
    /// gives 15, a factor of twenty, on every fault regardless of geometry.
    pub rake_sigma_deg: f32,
}

/// How rupture time and rise time relate to slip.
#[derive(Clone, Copy, Debug)]
pub struct TimingSpec {
    /// Correlation and spread of the rupture-time perturbation.
    pub rupture_time: PerturbationSpec,
    /// Amplitude applied to that perturbation, in seconds. Negative, so patches
    /// that slip more rupture earlier.
    pub rupture_time_scale: f32,
    /// Constant offset added to every onset time.
    pub rupture_delay_s: f32,
    /// How rise time is built.
    pub rise_time: RiseTimeSpec,
    /// How rise time stretches with depth.
    pub rise_time_stretch: RiseTimeStretch,
    /// How the fault-wide rise-time constant is averaged.
    pub rise_time_weighting: Weighting,
    /// Depth profile of rupture speed.
    pub speed_profile: SpeedProfile,
    /// Shape parameter of the slip-rate pulse.
    pub beta: BetaProfile,
    /// Sample interval of the slip-rate functions, in seconds.
    pub sample_interval_s: f32,
    /// Cap on samples per pulse.
    pub max_samples: usize,
}

/// A generated rupture model.
#[derive(Clone, Debug)]
pub struct RuptureModel {
    /// Slip in centimetres.
    pub slip: ScaledSlip,
    /// Rake in degrees.
    pub rake_deg: SlipField,
    /// Rupture onset in seconds, zero at the hypocentre.
    pub onset_s: TravelTimes,
    /// Rise time in seconds.
    pub rise_time_s: SlipField,
    /// One slip-rate pulse per subfault, along-strike index fastest.
    pub slip_rate: Vec<SlipRate>,
    /// The seismic moment the field was scaled to, in dyne-cm.
    pub moment_dyne_cm: f32,
    /// The dip-and-rake correction that was applied.
    pub alpha_t: f32,
}

/// Generate one rupture model.
///
/// `source` is the draw stream, already positioned at this realisation — see
/// [`crate::rng::Realisations`].
///
/// # Panics
///
/// If the fault grid's per-subfault arrays disagree with its extents.
#[expect(
    clippy::too_many_arguments,
    reason = "each argument is a distinct group; collapsing them would rebuild the \
              21-field god object ENGINEERING_RULES.md rule 7 exists to keep out"
)]
#[must_use]
pub fn generate<S: DrawSource, F: Fft, E: EikonalSolver>(
    draws: &mut S,
    fft: &mut F,
    solver: &mut E,
    grid: &FaultGrid,
    velocity_model: &VelocityModel,
    spec: SourceSpec,
    slip_spec: SlipSpec,
    timing: TimingSpec,
    hypocentre: Hypocentre,
) -> RuptureModel {
    let extents = grid.extents;
    let (strike_count, dip_count) = (extents.fault_strike, extents.fault_dip);
    let subfaults = strike_count * dip_count;
    assert_eq!(grid.depth_km.len(), dip_count, "one depth per dip row");
    assert_eq!(
        grid.base_rake_deg.len(),
        subfaults,
        "one base rake per subfault"
    );
    assert_eq!(
        grid.velocity_fraction.len(),
        subfaults,
        "one velocity fraction per subfault"
    );

    let derived = derive(spec, slip_spec.spectrum);
    let spectrum = derived.spectrum;
    let (shear_speed, rigidity) = velocity_model.sample(strike_count, &grid.depth_km);

    // --- slip -------------------------------------------------------------------
    let generated = slip::generate_normalised(draws, fft, extents, grid.spacing, spectrum);
    let original = generated.padded;
    let mut slip = generated.field;
    if slip_spec.truncate_negative {
        slip::truncate_negative_slip(&mut slip);
    }
    crate::taper::taper_edges(&mut slip, &slip_spec.tapers);
    if slip_spec.water_level > 0.0 {
        #[expect(clippy::cast_precision_loss, reason = "subfault counts are small")]
        let mean = slip.as_slice().iter().sum::<f32>() / subfaults as f32;
        slip::apply_water_level(&mut slip, mean, slip_spec.water_level);
    }

    let scaled = moment::scale_slip(
        &slip,
        0,
        dip_count,
        rigidity.as_slice(),
        SubfaultSize {
            strike_km: grid.spacing.strike_km,
            dip_km: grid.spacing.dip_km,
        },
        SlipScaling::Moment {
            dyne_cm: derived.moment_dyne_cm,
        },
    );

    // The perturbations correlate against the slip field as it now stands, not the
    // one the generator produced -- but mapped back onto the statistics that one had.
    let reference = slip::reload_for_correlation(&slip, fft, extents, grid.spacing, original);

    // --- rake, then the two perturbations, in the order the draws come off -------
    let rake_deg = slip::rake_field(
        draws,
        fft,
        extents,
        grid.spacing,
        spectrum,
        &grid.base_rake_deg,
        slip_spec.rake_sigma_deg,
    );

    let rupture_perturbation = slip::correlated_perturbation(
        draws,
        fft,
        &reference,
        extents,
        grid.spacing,
        spectrum,
        timing.rupture_time,
    );

    let rise_correlated = slip::correlated_field_on_fault(
        draws,
        fft,
        &reference,
        extents,
        grid.spacing,
        spectrum,
        timing.rise_time.perturbation.correlation,
    );

    // Two fields the original generates and never uses. Their draws are not
    // optional -- see `slip::skip_unused_field`.
    let refined = extents.padded_strike.max(extents.padded_dip) * 3;
    slip::skip_unused_field(draws, refined, refined);
    slip::skip_unused_field(draws, refined, refined);

    // The original inverse-transforms `slip_c` in place once both correlations have
    // finished with it (`genslip_v5.6.2.c:2225`), and the shallow rise-time blend
    // reads that spatial field rather than the tapered one the reload was built
    // from. The two differ by the reload's renormalisation, which is not a scalar.
    let reference_slip = slip::reference_on_fault(&reference, fft, extents, grid.spacing);

    assemble(
        &Drawn {
            scaled,
            rake_deg: rake_deg.clone(),
            rupture_perturbation,
            rise_correlated,
            reference_slip,
        },
        grid,
        &shear_speed,
        timing,
        &derived,
        solver,
        hypocentre,
    )
}

/// What the magnitude and geometry imply, before anything is drawn.
struct Derived {
    moment_dyne_cm: f32,
    alpha_t: f32,
    average_rise_time_s: f32,
    spectrum: SpectrumSpec,
}

fn derive(spec: SourceSpec, mut spectrum: SpectrumSpec) -> Derived {
    let moment_dyne_cm = source::seismic_moment(spec.magnitude, spec.magnitude_scale);
    let correction = source::geometry_correction(spec.average_dip_deg, spec.average_rake_deg);
    let corners = source::correlation_lengths(spec.magnitude, spec.corners, spec.modified_corners);

    spectrum.correlation = crate::field::CorrelationLengths {
        strike: corners.strike_km,
        dip: corners.dip_km,
    };

    Derived {
        moment_dyne_cm,
        alpha_t: correction.alpha_t,
        // The same correction shortens rise time and, at the caller, raises rupture
        // speed. Applying it in one place keeps the two from drifting apart.
        average_rise_time_s: source::average_rise_time(moment_dyne_cm, spec.rise_time_coefficient)
            * correction.alpha_t,
        spectrum,
    }
}

/// Everything the draw sequence produced, in the order it produced it.
struct Drawn {
    scaled: ScaledSlip,
    rake_deg: SlipField,
    rupture_perturbation: SlipField,
    rise_correlated: SlipField,
    /// The reloaded slip spectrum, back in space. What the shallow rise-time blend
    /// reads -- see `slip::reference_on_fault`.
    reference_slip: SlipField,
}

/// Turn the drawn fields into a rupture model. Nothing here draws.
fn assemble<E: EikonalSolver>(
    drawn: &Drawn,
    grid: &FaultGrid,
    shear_speed: &SlipField,
    timing: TimingSpec,
    derived: &Derived,
    solver: &mut E,
    hypocentre: Hypocentre,
) -> RuptureModel {
    let (strike_count, dip_count) = (grid.extents.fault_strike, grid.extents.fault_dip);
    let Drawn {
        scaled,
        rake_deg,
        rupture_perturbation,
        rise_correlated,
        reference_slip,
    } = drawn;
    let subfaults = strike_count * dip_count;

    // --- rise time --------------------------------------------------------------
    let normalised_rise = rise_time::rise_time_field(
        rise_correlated,
        reference_slip,
        &grid.depth_km,
        timing.rise_time,
    );
    let normalisation = rise_time::rise_time_normalisation(
        &normalised_rise,
        &scaled.slip,
        &grid.depth_km,
        &column_of(shear_speed),
        DepthScaling {
            stretch: timing.rise_time_stretch,
            rupture_velocity_fraction: grid.velocity_fraction[0],
            shallow_rupture_velocity: timing.speed_profile.shallow_factor,
            deep_rupture_velocity: timing.speed_profile.deep_factor,
        },
        timing.rise_time_weighting,
    );
    let rise_time_s = slip_rate::rise_times(
        &normalised_rise,
        &grid.depth_km,
        timing.rise_time_stretch,
        derived.average_rise_time_s,
        normalisation,
        timing.sample_interval_s,
    );

    // --- rupture times ----------------------------------------------------------
    let velocity_fraction =
        SlipField::from_values(strike_count, dip_count, grid.velocity_fraction.clone());
    let speed = rupture::speed_field(
        shear_speed,
        &velocity_fraction,
        &grid.depth_km,
        timing.speed_profile,
    );
    let travel = solver.solve(&speed, hypocentre, f64::from(grid.spacing.strike_km));
    let onset_s = rupture::onset_times(
        &travel,
        rupture_perturbation,
        OnsetAdjustment {
            perturbation_scale: timing.rupture_time_scale,
            delay_s: timing.rupture_delay_s,
            contains_hypocentre: true,
        },
    );

    // --- slip-rate pulses -------------------------------------------------------
    let beta = slip_rate::beta_field(strike_count, &grid.depth_km, timing.beta);
    let mut slip_rate = Vec::with_capacity(subfaults);
    for dip in 0..dip_count {
        for strike in 0..strike_count {
            // The original guards the whole generator on `|slip| > MINSLIP`
            // (`gslip_srf_subs.c:1496`) and writes `nt1 = 0` otherwise. The guard is
            // in the loader, not in `gen_OliuP2_stf`, so reproducing the generator
            // faithfully does not reproduce this — a subfault that does not slip was
            // getting a three-sample spike where the original writes no samples at
            // all. On a tapered fault that is every edge subfault: 21 of 240 on the
            // smallest corpus case, 108 of 1152 on the largest.
            let cm = scaled.slip[(strike, dip)];
            slip_rate.push(if cm.abs() > slip_rate::MIN_SLIP_CM {
                slip_rate::oliu_p(
                    cm,
                    rise_time_s[(strike, dip)],
                    beta[(strike, dip)],
                    timing.sample_interval_s,
                    timing.max_samples,
                )
            } else {
                SlipRate::empty()
            });
        }
    }

    RuptureModel {
        slip: scaled.clone(),
        rake_deg: rake_deg.clone(),
        onset_s,
        rise_time_s,
        slip_rate,
        moment_dyne_cm: derived.moment_dyne_cm,
        alpha_t: derived.alpha_t,
    }
}

/// One value per dip row, taken from the first subfault of each.
///
/// The properties this pulls out are constant along strike for a planar segment, and
/// the original reads them the same way.
fn column_of(field: &SlipField) -> Vec<f32> {
    (0..field.dip_count()).map(|dip| field[(0, dip)]).collect()
}
