//! One rupture model, start to finish.
//!
//! Every module before this does one stage. This runs them in order and is the only
//! place that order is written down — in the original it is spread across a
//! 2,859-line `main`.
//!
//! ```text
//!   slip          generate -> truncate -> taper -> scale to moment
//!   reload        the scaled field, back to the wavenumber domain
//!   rake          generated independently of slip
//!   rupture time  correlated with slip, centred, scaled
//!   rise time     correlated with slip, blended toward it near the surface
//!   (two fields   generated by the original and never used -- their draws are
//!    skipped)      consumed, their values are not)
//!   rupture speed from shear speed and depth
//!   onset         eikonal solve, then the rupture-time perturbation
//!   slip rate     one pulse per subfault
//! ```
//!
//! # Two ways in, one assembler
//!
//! [`generate`] draws four fields off one stream. [`point_source`] builds the same
//! four as constants and draws nothing. Both hand them to `assemble`, which is
//! everything downstream of the randomness — the depth ramp, the eikonal solve, the
//! pulses — so a point source is not a second pipeline but the same one with its
//! random inputs made trivial.
//!
//! # The order is a contract, not a preference
//!
//! Every stochastic field comes off one generator. Reordering two of them, or
//! skipping one without consuming its draws, changes every field after it — while
//! still producing output that looks entirely plausible. That is why the two unused
//! fields are skipped explicitly rather than deleted, and why this function is the
//! one place the sequence lives.
//!
//! (orig. `genslip_v5.6.2.c:1654-3202`)

use crate::fft::Fft;
use crate::moment::{self, ScaledSlip, SlipScaling, SubfaultSize};
use crate::rise_time::{self, DepthScaling, RiseTimeSpec, RiseTimeStretch, Weighting};
use crate::rng::DrawSource;
use crate::rupture::{self, EikonalSolver, Hypocentre, OnsetAdjustment, SpeedProfile, TravelTimes};
use crate::slip::{self, GridExtents, PerturbationSpec, SpectrumSpec, SubfaultSpacing};
use crate::slip_rate::{self, BetaProfile, SlipRate, SlipRateShape};
use crate::source::{self, CornerRelation, MagnitudeScale, VelocityModel};
use crate::taper::{EdgeTapers, SlipField};

/// The discretised fault: extents, spacing, and what varies down dip.
///
/// Depth and base rake come from the geometry module rather than being derived here,
/// because a fault is a mesh before it is a grid and only the caller knows how it was
/// discretised.
#[derive(Clone, Debug)]
pub struct FaultGrid {
    pub extents: GridExtents,
    pub spacing: SubfaultSpacing,
    /// One depth per dip row, in km. genslip reads depth per row too — from the first
    /// subfault of each — which is exact for a planar segment.
    pub depth_km: Vec<f32>,
    /// One rake per subfault, in degrees, before the rake field perturbs it.
    pub base_rake_deg: Vec<f32>,
    /// Rupture speed as a fraction of shear-wave speed, per subfault.
    pub velocity_fraction: Vec<f32>,
}

/// What the earthquake is, before any field is drawn.
#[derive(Clone, Copy, Debug)]
pub struct SourceSpec {
    pub magnitude: f32,
    pub magnitude_scale: MagnitudeScale,
    pub corners: CornerRelation,
    pub modified_corners: bool,
    /// Coefficient in `trise = c * 1e-9 * Mo^(1/3)`.
    pub rise_time_coefficient: f32,
    /// Average dip and rake, for the geometry correction.
    pub average_dip_deg: f32,
    pub average_rake_deg: f32,
}

/// How the slip and rake fields are shaped and trimmed.
///
/// Rake lives here rather than in `SourceSpec` because it is a *field*: drawn off the
/// same generator, filtered through the same `spectrum`. Only its normalisation
/// differs, and that difference is the whole of `rake_sigma_deg`.
#[derive(Clone, Copy, Debug)]
pub struct SlipSpec {
    pub spectrum: SpectrumSpec,
    pub tapers: EdgeTapers,
    /// Clip negative slip to zero. Configured on.
    pub truncate_negative: bool,
    /// Minimum slip as a fraction of the mean. Non-positive disables.
    pub water_level: f32,
    /// Standard deviation of the rake field, in **degrees**, about each subfault's
    /// base rake. (orig. `genslip_v5.6.2.c:2068`)
    ///
    /// Not `spectrum.coefficient_of_variation`, which is the *slip* field's spread
    /// and is dimensionless. Handing that to `rake_field` is what `DEFECTS.md` 14
    /// was: every rake came out with a spread of 0.75 degrees where the original
    /// gives 15, a factor of twenty, on every fault regardless of geometry.
    pub rake_sigma_deg: f32,
}

/// How rupture time and rise time relate to slip.
#[derive(Clone, Copy, Debug)]
pub struct TimingSpec {
    /// Correlation and spread of the rupture-time perturbation.
    pub rupture_time: PerturbationSpec,
    /// Amplitude applied to that perturbation, in seconds. Negative, so patches
    /// that slip more rupture earlier.
    pub rupture_time_scale: f32,
    /// Constant offset added to every onset time.
    pub rupture_delay_s: f32,
    /// How rise time is built.
    pub rise_time: RiseTimeSpec,
    /// How rise time stretches with depth.
    pub rise_time_stretch: RiseTimeStretch,
    /// How the fault-wide rise-time constant is averaged.
    pub rise_time_weighting: Weighting,
    /// Depth profile of rupture speed.
    pub speed_profile: SpeedProfile,
    /// Which slip-rate function every subfault gets.
    pub slip_rate_shape: SlipRateShape,
    /// Shape parameter of the slip-rate pulse. Read only by
    /// [`SlipRateShape::OliuP2`]; the others carry their own.
    pub beta: BetaProfile,
    /// Sample interval of the slip-rate functions, in seconds.
    pub sample_interval_s: f32,
    /// Cap on samples per pulse.
    pub max_samples: usize,
}

/// What the magnitude and geometry imply, before anything is drawn.
///
/// The three numbers [`assemble`] needs from the source description, and the reason
/// it needs nothing else from it. A finite fault derives all three from a magnitude;
/// a point source derives the first two the same way and is *given* the third.
#[derive(Clone, Copy, Debug)]
pub struct Scaling {
    /// Seismic moment, in dyne-cm.
    pub moment_dyne_cm: f32,
    /// The dip-and-rake geometry correction.
    pub alpha_t: f32,
    /// Fault-wide average rise time, in seconds, before the depth ramp redistributes
    /// it. Already multiplied by `alpha_t` where that applies.
    pub average_rise_time_s: f32,
}

/// A generated rupture model.
#[derive(Clone, Debug)]
pub struct RuptureModel {
    /// Slip in centimetres.
    pub slip: ScaledSlip,
    /// Rake in degrees.
    pub rake_deg: SlipField,
    /// Rupture onset in seconds, zero at the hypocentre.
    pub onset_s: TravelTimes,
    /// Rise time in seconds.
    pub rise_time_s: SlipField,
    /// One slip-rate pulse per subfault, along-strike index fastest.
    pub slip_rate: Vec<SlipRate>,
    /// The seismic moment the field was scaled to, in dyne-cm.
    pub moment_dyne_cm: f32,
    /// The dip-and-rake correction that was applied.
    pub alpha_t: f32,
}

/// Generate one rupture model.
///
/// `source` is the draw stream, already positioned at this realisation — see
/// [`crate::rng::Realisations`].
///
/// # Panics
///
/// If the fault grid's per-subfault arrays disagree with its extents.
#[expect(
    clippy::too_many_arguments,
    reason = "each argument is a distinct group; collapsing them would rebuild the \
              21-field god object ENGINEERING_RULES.md rule 7 exists to keep out"
)]
#[must_use]
pub fn generate<S: DrawSource, F: Fft, E: EikonalSolver>(
    draws: &mut S,
    fft: &mut F,
    solver: &mut E,
    grid: &FaultGrid,
    velocity_model: &VelocityModel,
    spec: SourceSpec,
    slip_spec: SlipSpec,
    timing: TimingSpec,
    hypocentre: Hypocentre,
) -> RuptureModel {
    let extents = grid.extents;
    let (strike_count, dip_count) = (extents.fault_strike, extents.fault_dip);
    let subfaults = strike_count * dip_count;
    assert_eq!(grid.depth_km.len(), dip_count, "one depth per dip row");
    assert_eq!(
        grid.base_rake_deg.len(),
        subfaults,
        "one base rake per subfault"
    );
    assert_eq!(
        grid.velocity_fraction.len(),
        subfaults,
        "one velocity fraction per subfault"
    );

    let (scaling, spectrum) = derive(spec, slip_spec.spectrum);
    let (shear_speed, rigidity) = velocity_model.sample(strike_count, &grid.depth_km);

    // --- slip -------------------------------------------------------------------
    let generated = slip::generate_normalised(draws, fft, extents, grid.spacing, spectrum);
    let original = generated.padded;
    let mut slip = generated.field;
    if slip_spec.truncate_negative {
        slip::truncate_negative_slip(&mut slip);
    }
    crate::taper::taper_edges(&mut slip, &slip_spec.tapers);
    if slip_spec.water_level > 0.0 {
        #[expect(clippy::cast_precision_loss, reason = "subfault counts are small")]
        let mean = slip.as_slice().iter().sum::<f32>() / subfaults as f32;
        slip::apply_water_level(&mut slip, mean, slip_spec.water_level);
    }

    let scaled = moment::scale_slip(
        &slip,
        0,
        dip_count,
        rigidity.as_slice(),
        SubfaultSize {
            strike_km: grid.spacing.strike_km,
            dip_km: grid.spacing.dip_km,
        },
        SlipScaling::Moment {
            dyne_cm: scaling.moment_dyne_cm,
        },
    );

    // The perturbations correlate against the slip field as it now stands, not the
    // one the generator produced -- but mapped back onto the statistics that one had.
    let reference = slip::reload_for_correlation(&slip, fft, extents, grid.spacing, original);

    // --- rake, then the two perturbations, in the order the draws come off -------
    let rake_deg = slip::rake_field(
        draws,
        fft,
        extents,
        grid.spacing,
        spectrum,
        &grid.base_rake_deg,
        slip_spec.rake_sigma_deg,
    );

    let rupture_perturbation = slip::correlated_perturbation(
        draws,
        fft,
        &reference,
        extents,
        grid.spacing,
        spectrum,
        timing.rupture_time,
    );

    let rise_correlated = slip::correlated_field_on_fault(
        draws,
        fft,
        &reference,
        extents,
        grid.spacing,
        spectrum,
        timing.rise_time.perturbation.correlation,
    );

    // Two fields the original generates and never uses. Their draws are not
    // optional -- see `slip::skip_unused_field`.
    let refined = extents.padded_strike.max(extents.padded_dip) * 3;
    slip::skip_unused_field(draws, refined, refined);
    slip::skip_unused_field(draws, refined, refined);

    // The original inverse-transforms `slip_c` in place once both correlations have
    // finished with it (`genslip_v5.6.2.c:2225`), and the shallow rise-time blend
    // reads that spatial field rather than the tapered one the reload was built
    // from. The two differ by the reload's renormalisation, which is not a scalar.
    let reference_slip = slip::reference_on_fault(&reference, fft, extents, grid.spacing);

    // The last thing the draws feed. It lives here rather than in `assemble` because
    // it is the one stage that *needs* a drawn field: it normalises to a prescribed
    // coefficient of variation, so a constant input divides by zero. Everything after
    // it works on any field, drawn or not.
    let normalised_rise = rise_time::rise_time_field(
        &rise_correlated,
        &reference_slip,
        &grid.depth_km,
        timing.rise_time,
    );

    assemble(
        &Fields {
            slip: scaled,
            rake_deg,
            normalised_rise,
            rupture_perturbation,
        },
        grid,
        &shear_speed,
        timing,
        scaling,
        solver,
        hypocentre,
    )
}

/// What a point source is, over and above its geometry.
///
/// Deliberately small, and deliberately not [`SourceSpec`]: there is no spectrum
/// here, so there are no corner relations and no coefficient turning a moment into a
/// rise time. A point source is told its rise time.
#[derive(Clone, Copy, Debug)]
pub struct PointSourceSpec {
    pub magnitude: f32,
    pub magnitude_scale: MagnitudeScale,
    /// Average dip and rake, for the same geometry correction a finite fault gets.
    pub average_dip_deg: f32,
    pub average_rake_deg: f32,
    /// Fault-wide average rise time, in seconds — `generic_slip2srf`'s `risetime`.
    ///
    /// The *average*, which the depth ramp then redistributes around. The original
    /// treats it as the unstretched value instead, so its ramp can only ever lengthen
    /// and the fault-wide average comes out above what was asked for. Redistributing
    /// is what the finite-fault path does and what makes a one-subfault source come
    /// out at exactly this number.
    pub rise_time_s: f32,
}

/// Generate a point source: the same rupture model, with nothing drawn.
///
/// A point source is a plane with **constant slip, constant rake and no
/// perturbations** — `generic_slip2srf` is handed exactly that, one slip value and
/// one onset repeated over however many subfaults the geometry discretised into. So
/// this is not a second pipeline. It builds the four [`Fields`] as constants and
/// hands them to the same [`assemble`] a finite fault reaches, and everything
/// downstream — the depth ramp, the fault-wide normalisation, the eikonal solve, the
/// pulses, the moment — is the code that was already there and already tested.
///
/// The signature is the argument. There is no [`DrawSource`] and no [`Fft`], because
/// nothing here is random; there is no [`SlipSpec`], because there is no spectrum to
/// shape, no taper and no spread. What is left is a fault, a velocity model, a
/// magnitude and a rise time.
///
/// # Where this differs from `generic_slip2srf`, on purpose
///
/// **Onset is solved for, not given.** The C writes one `inittime` at every subfault;
/// this runs the eikonal solver from the hypocentre and adds
/// [`TimingSpec::rupture_delay_s`]. For a genuinely single-subfault source the two
/// agree exactly — the solve gives zero and the delay is the onset. For a
/// discretised plane the C has a rupture that arrives everywhere at once, and this
/// has a front. The velocity model is right there; refusing to use it would be the
/// odd choice.
///
/// **Slip is moment-consistent per subfault.** `scale_slip` scales a uniform field so
/// the summed moment `Σ μᵢ Aᵢ sᵢ` is the target, so a fault crossing a layer boundary
/// gets the slip that carries the moment rather than the slip a single rigidity
/// lookup at the centroid implies.
///
/// # Panics
///
/// If the fault grid's per-subfault arrays disagree with its extents, or if
/// `rise_time_s` is not strictly positive.
#[must_use]
pub fn point_source<E: EikonalSolver>(
    solver: &mut E,
    grid: &FaultGrid,
    velocity_model: &VelocityModel,
    spec: PointSourceSpec,
    timing: TimingSpec,
    hypocentre: Hypocentre,
) -> RuptureModel {
    let (strike_count, dip_count) = (grid.extents.fault_strike, grid.extents.fault_dip);
    let subfaults = strike_count * dip_count;
    assert_eq!(grid.depth_km.len(), dip_count, "one depth per dip row");
    assert_eq!(
        grid.base_rake_deg.len(),
        subfaults,
        "one base rake per subfault"
    );
    assert_eq!(
        grid.velocity_fraction.len(),
        subfaults,
        "one velocity fraction per subfault"
    );
    assert!(
        spec.rise_time_s > 0.0,
        "the average rise time must be positive"
    );

    let correction = source::geometry_correction(spec.average_dip_deg, spec.average_rake_deg);
    let scaling = Scaling {
        moment_dyne_cm: source::seismic_moment(spec.magnitude, spec.magnitude_scale),
        alpha_t: correction.alpha_t,
        // Given, not derived. The finite-fault path multiplies its `Mo^(1/3)` estimate
        // by `alpha_t` because the correction is *part of* that estimate; a rise time
        // the caller measured or chose has already accounted for the geometry, and
        // shortening it again would be applying the correction twice.
        average_rise_time_s: spec.rise_time_s,
    };

    let (shear_speed, rigidity) = velocity_model.sample(strike_count, &grid.depth_km);

    // Uniform slip, scaled so the summed moment is the target. A field of ones and the
    // same scaler the finite-fault path uses -- what makes this a point *source*
    // rather than a point is that the moment still has to come out right.
    let uniform = SlipField::from_values(strike_count, dip_count, vec![1.0; subfaults]);
    let slip = moment::scale_slip(
        &uniform,
        0,
        dip_count,
        rigidity.as_slice(),
        SubfaultSize {
            strike_km: grid.spacing.strike_km,
            dip_km: grid.spacing.dip_km,
        },
        SlipScaling::Moment {
            dyne_cm: scaling.moment_dyne_cm,
        },
    );

    assemble(
        &Fields {
            slip,
            rake_deg: SlipField::from_values(strike_count, dip_count, grid.base_rake_deg.clone()),
            // Unit mean by construction, so `rise_time_normalisation` returns the mean
            // of the depth factor and `rise_times` gives back exactly
            // `factor_at(depth) / mean(factor_at) * rise_time_s`.
            normalised_rise: uniform,
            rupture_perturbation: SlipField::zeros(strike_count, dip_count),
        },
        grid,
        &shear_speed,
        timing,
        scaling,
        solver,
        hypocentre,
    )
}

/// Resolve a magnitude into a moment, a correction and an average rise time, and fill
/// in the correlation lengths the spectrum was missing.
///
/// The spectrum comes back separately because it is the one output nothing downstream
/// of the draws reads: [`assemble`] takes the [`Scaling`] and never sees it.
fn derive(spec: SourceSpec, mut spectrum: SpectrumSpec) -> (Scaling, SpectrumSpec) {
    let moment_dyne_cm = source::seismic_moment(spec.magnitude, spec.magnitude_scale);
    let correction = source::geometry_correction(spec.average_dip_deg, spec.average_rake_deg);
    let corners = source::correlation_lengths(spec.magnitude, spec.corners, spec.modified_corners);

    spectrum.correlation = crate::field::CorrelationLengths {
        strike: corners.strike_km,
        dip: corners.dip_km,
    };

    (
        Scaling {
            moment_dyne_cm,
            alpha_t: correction.alpha_t,
            // The same correction shortens rise time and, at the caller, raises rupture
            // speed. Applying it in one place keeps the two from drifting apart.
            average_rise_time_s: source::average_rise_time(
                moment_dyne_cm,
                spec.rise_time_coefficient,
            ) * correction.alpha_t,
        },
        spectrum,
    )
}

/// The four fields a rupture is assembled from.
///
/// The seam between *where the numbers came from* and *what is done with them*. A
/// finite fault draws all four off one generator; a point source builds all four as
/// constants. Everything downstream is the same code, which is the whole reason this
/// struct exists rather than [`assemble`] taking the drawn fields directly.
struct Fields {
    slip: ScaledSlip,
    rake_deg: SlipField,
    /// Dimensionless, unit mean. `rise_time_field` builds it for a finite fault; a
    /// point source passes ones, which is the one thing that *cannot* be expressed as
    /// a degenerate input -- `rise_time_field` normalises to a prescribed spread and
    /// so divides by a constant field's zero variation.
    normalised_rise: SlipField,
    /// Added to the eikonal solve's travel times. Zero for a point source.
    rupture_perturbation: SlipField,
}

/// Turn four fields into a rupture model. Nothing here draws, and nothing here knows
/// whether anything did.
///
/// This is the whole of the pipeline downstream of the randomness: rise time, the
/// eikonal solve, and one pulse per subfault. [`generate`] reaches it with drawn
/// fields and [`point_source`] with constant ones, and the two produce the same kind
/// of answer because they run the same code rather than an agreeing copy of it.
fn assemble<E: EikonalSolver>(
    fields: &Fields,
    grid: &FaultGrid,
    shear_speed: &SlipField,
    timing: TimingSpec,
    scaling: Scaling,
    solver: &mut E,
    hypocentre: Hypocentre,
) -> RuptureModel {
    let (strike_count, dip_count) = (grid.extents.fault_strike, grid.extents.fault_dip);
    let Fields {
        slip: scaled,
        rake_deg,
        normalised_rise,
        rupture_perturbation,
    } = fields;
    let subfaults = strike_count * dip_count;

    // --- rise time --------------------------------------------------------------
    let normalisation = rise_time::rise_time_normalisation(
        normalised_rise,
        &scaled.slip,
        &grid.depth_km,
        &column_of(shear_speed),
        DepthScaling {
            stretch: timing.rise_time_stretch,
            rupture_velocity_fraction: grid.velocity_fraction[0],
            shallow_rupture_velocity: timing.speed_profile.shallow_factor,
            deep_rupture_velocity: timing.speed_profile.deep_factor,
        },
        timing.rise_time_weighting,
    );
    let rise_time_s = slip_rate::rise_times(
        normalised_rise,
        &grid.depth_km,
        timing.rise_time_stretch,
        scaling.average_rise_time_s,
        normalisation,
        timing.sample_interval_s,
    );

    // --- rupture times ----------------------------------------------------------
    let velocity_fraction =
        SlipField::from_values(strike_count, dip_count, grid.velocity_fraction.clone());
    let speed = rupture::speed_field(
        shear_speed,
        &velocity_fraction,
        &grid.depth_km,
        timing.speed_profile,
    );
    let travel = solver.solve(&speed, hypocentre, f64::from(grid.spacing.strike_km));
    let mut onset_s = rupture::onset_times(
        &travel,
        rupture_perturbation,
        OnsetAdjustment {
            perturbation_scale: timing.rupture_time_scale,
            delay_s: timing.rupture_delay_s,
            contains_hypocentre: true,
        },
    );

    // --- slip-rate pulses -------------------------------------------------------
    let shape = timing.slip_rate_shape;
    let shape_parameter =
        slip_rate::shape_parameter_field(shape, strike_count, &grid.depth_km, timing.beta);
    let mut slip_rate = Vec::with_capacity(subfaults);
    let mut onset_shift_s = Vec::with_capacity(subfaults);
    for dip in 0..dip_count {
        for strike in 0..strike_count {
            // The original guards the whole generator on `|slip| > MINSLIP`
            // (`gslip_srf_subs.c:1496`) and writes `nt1 = 0` otherwise. The guard is
            // in the loader, not in `gen_OliuP2_stf`, so reproducing the generator
            // faithfully does not reproduce this — a subfault that does not slip was
            // getting a three-sample spike where the original writes no samples at
            // all. On a tapered fault that is every edge subfault: 21 of 240 on the
            // smallest corpus case, 108 of 1152 on the largest.
            let cm = scaled.slip[(strike, dip)];
            slip_rate.push(if cm.abs() > slip_rate::MIN_SLIP_CM {
                shape.pulse(
                    cm,
                    rise_time_s[(strike, dip)],
                    shape_parameter[(strike, dip)],
                    timing.sample_interval_s,
                    timing.max_samples,
                )
            } else {
                SlipRate::empty()
            });
            // Non-causal shapes radiate before their nominal start, so the arrival
            // moves back to meet them. Zero for every shape but `Seki`, and gathered
            // here rather than inside the pulse because it is a fact about *when*
            // rather than about the samples.
            onset_shift_s.push(shape.onset_shift_s(rise_time_s[(strike, dip)]));
        }
    }

    onset_s.shift(&onset_shift_s);

    RuptureModel {
        slip: scaled.clone(),
        rake_deg: rake_deg.clone(),
        onset_s,
        rise_time_s,
        slip_rate,
        moment_dyne_cm: scaling.moment_dyne_cm,
        alpha_t: scaling.alpha_t,
    }
}

/// One value per dip row, taken from the first subfault of each.
///
/// The properties this pulls out are constant along strike for a planar segment, and
/// the original reads them the same way.
fn column_of(field: &SlipField) -> Vec<f32> {
    (0..field.dip_count()).map(|dip| field[(0, dip)]).collect()
}
